# Compiler setup
COMPILER = g++
COMPILEMPI = mpicxx
FLAGS += -std=c++20 -O3 -Wall
INCLUDES += -I../include/ -I../include/spdlog/include

LINKS ?=

# Default target
all: 

# --- clean ---
.PHONY: clean
clean:
	
